<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class KoisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('kois')->delete();
        
        \DB::table('kois')->insert(array (
            0 => 
            array (
                'id' => 'RG2409008A',
                'auction_code' => 'RG2409008',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Corrupti',
                'jenis_koi' => 'Ai Goromo',
                'ukuran' => 35,
                'gender' => 'male',
                'open_bid' => '70.00',
                'kelipatan_bid' => '68.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Magna facilis eos te',
                'breeder' => 'Dolorem exercitation',
                'created_at' => '2024-09-15 09:17:51',
                'updated_at' => '2024-09-15 09:17:51',
            ),
            1 => 
            array (
                'id' => 'RG2409008B',
                'auction_code' => 'RG2409008',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'fugit',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 35,
                'gender' => 'male',
                'open_bid' => '70.00',
                'kelipatan_bid' => '68.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Magna facilis eos te',
                'breeder' => 'Dolorem exercitation',
                'created_at' => '2024-09-15 09:17:51',
                'updated_at' => '2024-09-15 09:17:51',
            ),
            2 => 
            array (
                'id' => 'RG2409008C',
                'auction_code' => 'RG2409008',
                'event_id' => NULL,
                'kode_ikan' => 'C',
                'judul' => 'Dolores',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 35,
                'gender' => 'male',
                'open_bid' => '70.00',
                'kelipatan_bid' => '68.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Magna facilis eos te',
                'breeder' => 'Dolorem exercitation',
                'created_at' => '2024-09-15 09:17:51',
                'updated_at' => '2024-09-15 09:17:51',
            ),
            3 => 
            array (
                'id' => 'RG2409008D',
                'auction_code' => 'RG2409008',
                'event_id' => NULL,
                'kode_ikan' => 'D',
                'judul' => 'SitAmet',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 35,
                'gender' => 'male',
                'open_bid' => '70.00',
                'kelipatan_bid' => '68.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Magna facilis eos te',
                'breeder' => 'Dolorem exercitation',
                'created_at' => '2024-09-15 09:17:51',
                'updated_at' => '2024-09-15 09:17:51',
            ),
            4 => 
            array (
                'id' => 'RG2409009A',
                'auction_code' => 'RG2409009',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Anim laboriosam',
                'jenis_koi' => 'Ai Goromo',
                'ukuran' => 40,
                'gender' => 'male',
                'open_bid' => '69.00',
                'kelipatan_bid' => '43.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Nemo qui qui qui vel',
                'breeder' => 'Anim voluptate qui o',
                'created_at' => '2024-09-15 12:04:43',
                'updated_at' => '2024-09-15 12:04:43',
            ),
            5 => 
            array (
                'id' => 'RG2409009B',
                'auction_code' => 'RG2409009',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'Quod irure',
                'jenis_koi' => 'Tancho Showa',
                'ukuran' => 69,
                'gender' => 'male',
                'open_bid' => '19.00',
                'kelipatan_bid' => '92.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Iure rerum asperiore',
                'breeder' => 'Eaque unde error lab',
                'created_at' => '2024-09-15 12:04:44',
                'updated_at' => '2024-09-15 12:04:44',
            ),
            6 => 
            array (
                'id' => 'RG2409009C',
                'auction_code' => 'RG2409009',
                'event_id' => NULL,
                'kode_ikan' => 'C',
                'judul' => 'Non ut',
                'jenis_koi' => 'Kawarimono B',
                'ukuran' => 3,
                'gender' => 'unchecked',
                'open_bid' => '94.00',
                'kelipatan_bid' => '51.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Dolorem fugit est',
                'breeder' => 'Delectus qui odio a',
                'created_at' => '2024-09-15 12:04:44',
                'updated_at' => '2024-09-15 12:04:44',
            ),
            7 => 
            array (
                'id' => 'RG2409009D',
                'auction_code' => 'RG2409009',
                'event_id' => NULL,
                'kode_ikan' => 'D',
                'judul' => 'Nihil aut',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 2,
                'gender' => 'female',
                'open_bid' => '89.00',
                'kelipatan_bid' => '91.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Reprehenderit dolor',
                'breeder' => 'Ipsum laboris ratio',
                'created_at' => '2024-09-15 12:04:44',
                'updated_at' => '2024-09-15 12:04:44',
            ),
            8 => 
            array (
                'id' => 'RG2409009E',
                'auction_code' => 'RG2409009',
                'event_id' => NULL,
                'kode_ikan' => 'E',
                'judul' => 'Iure rerum',
                'jenis_koi' => 'Asagi',
                'ukuran' => 7,
                'gender' => 'male',
                'open_bid' => '15.00',
                'kelipatan_bid' => '56.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Aut sed aut in aut e',
                'breeder' => 'Consectetur dolores',
                'created_at' => '2024-09-15 12:04:44',
                'updated_at' => '2024-09-15 12:04:44',
            ),
            9 => 
            array (
                'id' => 'RG2409011A',
                'auction_code' => 'RG2409011',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Quo ex ',
                'jenis_koi' => 'Shusui',
                'ukuran' => 50,
                'gender' => 'male',
                'open_bid' => '450.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Esse ut laborum exp',
                'breeder' => 'Quasi voluptatem ten',
                'created_at' => '2024-09-24 10:30:17',
                'updated_at' => '2024-09-24 10:30:17',
            ),
            10 => 
            array (
                'id' => 'RG2409011B',
                'auction_code' => 'RG2409011',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'Accusamus commodi',
                'jenis_koi' => 'Kinginrin A',
                'ukuran' => 10,
                'gender' => 'male',
                'open_bid' => '66.00',
                'kelipatan_bid' => '50.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Aspernatur veritatis',
                'breeder' => 'Alias quaerat delect',
                'created_at' => '2024-09-24 10:30:17',
                'updated_at' => '2024-09-24 10:30:17',
            ),
            11 => 
            array (
                'id' => 'RG2409011C',
                'auction_code' => 'RG2409011',
                'event_id' => NULL,
                'kode_ikan' => 'C',
                'judul' => 'Reiciendis vitae',
                'jenis_koi' => 'Hikari Utsurimono',
                'ukuran' => 31,
                'gender' => 'unchecked',
                'open_bid' => '250.00',
                'kelipatan_bid' => '10.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Adipisicing ab id a',
                'breeder' => 'Alias corrupti cons',
                'created_at' => '2024-09-24 10:30:17',
                'updated_at' => '2024-09-24 10:30:17',
            ),
            12 => 
            array (
                'id' => 'RG2409011D',
                'auction_code' => 'RG2409011',
                'event_id' => NULL,
                'kode_ikan' => 'D',
                'judul' => 'Aut voluptatibus',
                'jenis_koi' => 'Tancho Sanke',
                'ukuran' => 86,
                'gender' => 'unchecked',
                'open_bid' => '250.00',
                'kelipatan_bid' => '10.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Molestias et obcaeca',
                'breeder' => 'Enim magni magni est',
                'created_at' => '2024-09-24 10:30:17',
                'updated_at' => '2024-09-24 10:30:17',
            ),
            13 => 
            array (
                'id' => 'RG2410002A',
                'auction_code' => 'RG2410002',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Ikan Koi 1',
                'jenis_koi' => 'Taisho Sanshoku',
                'ukuran' => 48,
                'gender' => 'male',
                'open_bid' => '350.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Sehat rajin menabung',
                'breeder' => 'Yuki Koi',
                'created_at' => '2024-10-23 14:31:49',
                'updated_at' => '2024-10-23 14:31:49',
            ),
            14 => 
            array (
                'id' => 'RG2410002B',
                'auction_code' => 'RG2410002',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'Ikan Koi 2',
                'jenis_koi' => 'Taisho Sanshoku',
                'ukuran' => 44,
                'gender' => 'unchecked',
                'open_bid' => '350.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Sehat rajin sholat',
                'breeder' => 'Yuki Koi',
                'created_at' => '2024-10-23 14:31:49',
                'updated_at' => '2024-10-23 14:31:49',
            ),
            15 => 
            array (
                'id' => 'RG2410002C',
                'auction_code' => 'RG2410002',
                'event_id' => NULL,
                'kode_ikan' => 'C',
                'judul' => 'Ikan Koi 3',
                'jenis_koi' => 'Taisho Sanshoku',
                'ukuran' => 43,
                'gender' => 'male',
                'open_bid' => '350.00',
                'kelipatan_bid' => '50.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Sehat rajin menabung',
                'breeder' => 'Yuki Koi',
                'created_at' => '2024-10-23 14:31:49',
                'updated_at' => '2024-10-23 14:31:49',
            ),
            16 => 
            array (
                'id' => 'RG2410003A',
                'auction_code' => 'RG2410003',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Showa haha',
                'jenis_koi' => 'Showa Sanshoku',
                'ukuran' => 40,
                'gender' => 'male',
                'open_bid' => '150.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Dolorem lorem recusa',
                'breeder' => 'Magnam possimus non',
                'created_at' => '2024-10-27 14:58:45',
                'updated_at' => '2024-10-27 14:58:45',
            ),
            17 => 
            array (
                'id' => 'RG2410003B',
                'auction_code' => 'RG2410003',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'Showa hehe',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 42,
                'gender' => 'male',
                'open_bid' => '150.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Dolorem lorem recusa',
                'breeder' => 'Magnam possimus non',
                'created_at' => '2024-10-27 14:58:45',
                'updated_at' => '2024-10-27 14:58:45',
            ),
            18 => 
            array (
                'id' => 'RG2410003C',
                'auction_code' => 'RG2410003',
                'event_id' => NULL,
                'kode_ikan' => 'C',
                'judul' => 'Showa King',
                'jenis_koi' => 'Showa Sanshoku',
                'ukuran' => 50,
                'gender' => 'male',
                'open_bid' => '200.00',
                'kelipatan_bid' => '50.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Dolorem lorem recusa',
                'breeder' => 'Magnam possimus non',
                'created_at' => '2024-10-27 14:58:45',
                'updated_at' => '2024-12-11 19:01:45',
            ),
            19 => 
            array (
                'id' => 'RG2410003D',
                'auction_code' => 'RG2410003',
                'event_id' => NULL,
                'kode_ikan' => 'D',
                'judul' => 'Showa hoho',
                'jenis_koi' => 'Showa Sanshoku',
                'ukuran' => 50,
                'gender' => 'male',
                'open_bid' => '650.00',
                'kelipatan_bid' => '25.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Dolorem lorem recusa',
                'breeder' => 'Magnam possimus non',
                'created_at' => '2024-10-27 14:58:45',
                'updated_at' => '2024-10-27 14:58:45',
            ),
            20 => 
            array (
                'id' => 'RG2411001A',
                'auction_code' => 'RG2411001',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'Dolore accusantium',
                'jenis_koi' => 'Asagi',
                'ukuran' => 64,
                'gender' => 'male',
                'open_bid' => '79.00',
                'kelipatan_bid' => '61.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Sunt dolore nisi aut',
                'breeder' => 'Quia dicta explicabo',
                'created_at' => '2024-11-17 09:06:54',
                'updated_at' => '2024-11-17 09:06:54',
            ),
            21 => 
            array (
                'id' => 'RG2411001B',
                'auction_code' => 'RG2411001',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'nostrud non',
                'jenis_koi' => 'Kohaku',
                'ukuran' => 94,
                'gender' => 'unchecked',
                'open_bid' => '57.00',
                'kelipatan_bid' => '90.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Quis at sit qui sed',
                'breeder' => 'Ut culpa nisi in qui',
                'created_at' => '2024-11-17 09:06:55',
                'updated_at' => '2024-11-17 09:06:55',
            ),
            22 => 
            array (
                'id' => 'RG2412001A',
                'auction_code' => 'RG2412001',
                'event_id' => NULL,
                'kode_ikan' => 'A',
                'judul' => 'quisquam',
                'jenis_koi' => 'Kawarimono B',
                'ukuran' => 35,
                'gender' => 'unchecked',
                'open_bid' => '18.00',
                'kelipatan_bid' => '85.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Voluptatem ut venia',
                'breeder' => 'Dolor est do dolor c',
                'created_at' => '2025-02-15 13:08:47',
                'updated_at' => '2025-02-15 13:08:47',
            ),
            23 => 
            array (
                'id' => 'RG2412001B',
                'auction_code' => 'RG2412001',
                'event_id' => NULL,
                'kode_ikan' => 'B',
                'judul' => 'Aliquip veritatis',
                'jenis_koi' => 'Hi/Ki Utsurimono',
                'ukuran' => 42,
                'gender' => 'female',
                'open_bid' => '27.00',
                'kelipatan_bid' => '51.00',
                'buy_it_now' => '10000.00',
                'keterangan' => 'Non quibusdam pariat',
                'breeder' => 'Aliqua Laboris repr',
                'created_at' => '2025-02-15 20:36:55',
                'updated_at' => '2025-02-15 20:36:55',
            ),
        ));
        
        
    }
}