<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Heathcliff',
                'profile_photo' => 'profile_photos/80Dhj4nDPF5cgdJwHRSKOAANd5rs5ZUE2np1Bast.jpg',
                'avatar' => NULL,
                'email' => 'puremachine99@gmail.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => 'Knight Of Blood Oath',
                'address' => 'jl besi no 1 kav 1',
                'city' => 'Malang',
                'ktp_photo' => NULL,
                'nik' => '3573012511940005',
                'bank_name' => 'BCA',
                'bank_account' => NULL,
                'phone_number' => '082257111684',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OePmFTS5yCCfnMf3M/9iGOK08j0SQBzzLWjDkx49tjVzUKoH9u5Bi',
                'remember_token' => '08Ojd7CelSoNyu662hnL0NWSxLcNEVo39zQbJhl4Br2be2KYOPXN4UeHbBmK',
                'deleted_at' => NULL,
                'created_at' => '2024-09-12 14:10:03',
                'updated_at' => '2025-05-29 12:12:52',
                'role' => 'admin',
                'is_verified' => 0,
                'is_priority_seller' => 0,
                'subscription_start' => NULL,
                'subscription_end' => NULL,
                'bio' => 'Bukan Seller , seorang programmer yang menggunakan akun ini untuk testing fungsionalitas dari app yuki koi auction',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Yuki',
                'profile_photo' => 'profile_photos/26uMWqTHgqzVwv8KJM6MXFyZoOu5NyWTIZqxH0vm.png',
                'avatar' => NULL,
                'email' => 'bifysyk@mailinator.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => 'Yuki Koi Centre',
                'address' => 'jl Merdeka no 1 ',
                'city' => 'Blitar',
                'ktp_photo' => NULL,
                'nik' => '3463473453476345',
                'bank_name' => NULL,
                'bank_account' => NULL,
                'phone_number' => '081234321272',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OePmFTS5yCCfnMf3M/9iGOK08j0SQBzzLWjDkx49tjVzUKoH9u5Bi',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-13 15:48:53',
                'updated_at' => '2024-09-29 00:50:53',
                'role' => 'seller',
                'is_verified' => 0,
                'is_priority_seller' => 1,
                'subscription_start' => '2024-09-13 15:48:53',
                'subscription_end' => '2027-09-13 15:48:53',
                'bio' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Desiree Clay',
                'profile_photo' => NULL,
                'avatar' => NULL,
                'email' => 'dakycefa@mailinator.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => 'ClayFarm',
                'address' => 'Jl Lumpang no 29',
                'city' => 'Surabaya',
                'ktp_photo' => NULL,
                'nik' => '3463473453476346',
                'bank_name' => NULL,
                'bank_account' => NULL,
                'phone_number' => '082257111687',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OePmFTS5yCCfnMf3M/9iGOK08j0SQBzzLWjDkx49tjVzUKoH9u5Bi',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-15 09:13:41',
                'updated_at' => '2024-09-15 09:13:41',
                'role' => 'seller',
                'is_verified' => 0,
                'is_priority_seller' => 0,
                'subscription_start' => NULL,
                'subscription_end' => NULL,
                'bio' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Ali Hoffman',
                'profile_photo' => NULL,
                'avatar' => NULL,
                'email' => 'pakuvilaq@mailinator.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => 'Ali Farm',
                'address' => 'Jl. A yani 19',
                'city' => 'New York',
                'ktp_photo' => NULL,
                'nik' => '3463473453476347',
                'bank_name' => NULL,
                'bank_account' => NULL,
                'phone_number' => '082257111688',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OePmFTS5yCCfnMf3M/9iGOK08j0SQBzzLWjDkx49tjVzUKoH9u5Bi',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-15 11:58:34',
                'updated_at' => '2024-09-15 11:58:34',
                'role' => 'seller',
                'is_verified' => 0,
                'is_priority_seller' => 0,
                'subscription_start' => NULL,
                'subscription_end' => NULL,
                'bio' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Firda',
                'profile_photo' => 'profile_photos/KkCxVP0vJqwx1p5f3Y8SDhN7DbZkSVmHcTh96tpW.jpg',
                'avatar' => NULL,
                'email' => 'firdaa60@gmail.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => '99 Koi Farm',
                'address' => 'Jl Merdeka 19',
                'city' => 'Surabaya',
                'ktp_photo' => NULL,
                'nik' => '3573012345982919',
                'bank_name' => NULL,
                'bank_account' => NULL,
                'phone_number' => '082257111685',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OePmFTS5yCCfnMf3M/9iGOK08j0SQBzzLWjDkx49tjVzUKoH9u5Bi',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-19 15:35:01',
                'updated_at' => '2024-09-27 19:34:01',
                'role' => 'seller',
                'is_verified' => 0,
                'is_priority_seller' => 0,
                'subscription_start' => NULL,
                'subscription_end' => NULL,
                'bio' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Dion',
                'profile_photo' => 'profile_photos/Ixw0cr3XQcNgwH3ReJVVwsPvLBlLvr61l4HnW00y.jpg',
                'avatar' => NULL,
                'email' => 'ahsadhgasdf@gmail.com',
                'instagram' => NULL,
                'youtube' => NULL,
                'farm_name' => 'Barley BarberShop',
                'address' => 'Sanggrahan Lor, Kasembon, Kec. Kasembon, Kabupaten Malang, Jawa Timur 65393',
                'city' => 'Kasembon',
                'ktp_photo' => NULL,
                'nik' => '1278617264571625',
                'bank_name' => NULL,
                'bank_account' => NULL,
                'phone_number' => '085174390579',
                'is_seller' => 1,
                'pin' => '1234',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DNupOjpYAtrliVflytLL1OX9OQ6pxNAj/kumksFyIzORUGXgvheUW',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-09-30 16:14:34',
                'updated_at' => '2024-09-30 16:15:28',
                'role' => 'seller',
                'is_verified' => 0,
                'is_priority_seller' => 0,
                'subscription_start' => NULL,
                'subscription_end' => NULL,
                'bio' => NULL,
            ),
        ));
        
        
    }
}