@echo off
php artisan make:migration create_profiles_table
timeout /t 1 >nul
php artisan make:migration create_follows_table
timeout /t 1 >nul
php artisan make:migration create_fish_species_table
timeout /t 1 >nul
php artisan make:migration create_items_table
timeout /t 1 >nul
php artisan make:migration create_item_likes_table
timeout /t 1 >nul
php artisan make:migration create_item_shares_table
timeout /t 1 >nul
php artisan make:migration create_auctions_table
timeout /t 1 >nul
php artisan make:migration create_auction_lots_table
timeout /t 1 >nul
php artisan make:migration create_lot_items_table
timeout /t 1 >nul
php artisan make:migration create_bids_table
timeout /t 1 >nul
php artisan make:migration create_watchlists_table
timeout /t 1 >nul
php artisan make:migration create_rooms_table
timeout /t 1 >nul
php artisan make:migration create_messages_table
timeout /t 1 >nul
php artisan make:migration create_message_reactions_table
timeout /t 1 >nul
php artisan make:migration create_orders_table
timeout /t 1 >nul
php artisan make:migration create_order_items_table
timeout /t 1 >nul
php artisan make:migration create_payments_table
timeout /t 1 >nul
php artisan make:migration create_invoices_table
timeout /t 1 >nul
php artisan make:migration create_escrow_entries_table
timeout /t 1 >nul
php artisan make:migration create_auction_reports_table
timeout /t 1 >nul
php artisan make:migration create_audit_events_table
timeout /t 1 >nul
php artisan Make:model Profile
php artisan Make:model Follow
php artisan Make:model FishSpecies
php artisan Make:model Item
php artisan Make:model ItemLike
php artisan Make:model ItemShare
php artisan Make:model Auction
php artisan Make:model AuctionLot
php artisan Make:model LotItem
php artisan Make:model Bid
php artisan Make:model Watchlist
php artisan Make:model Room
php artisan Make:model Message
php artisan Make:model MessageReaction
php artisan Make:model Order
php artisan Make:model OrderItem
php artisan Make:model Payment
php artisan Make:model Invoice
php artisan Make:model EscrowEntry
php artisan Make:model AuctionReport
php artisan Make:model AuditEvent